version : "3"

services:
  view:
    image: view
    build: .
    env_file: 
      - .env
    volumes:
      - "./view/view:/view"
    command: ./view
    expose:
      - "8080"
    ports: 
      - "8383:8080"
    depends_on:
      - postgres
    networks:
      mynet:
        ipv4_address: "172.28.1.3"

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"
    ports: 
      - "15432:5432"
    networks:
      mynet:
        ipv4_address: "172.28.1.10"
    
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/16"