version : "3"

services:
  update:
    image: update
    build: .
    env_file: 
      - .env
    volumes:
      - "./update/update:/update"
    command: ./update
    expose:
      - "8080"
    ports: 
      - "8181:8080"
    depends_on:
      - postgres
    networks:
      mynet:
        ipv4_address: "172.28.1.1"
  create:
    image: create
    build: .
    env_file: 
      - .env
    volumes:
      - "./create/create:/create"
    command: ./create
    expose:
      - "8080"
    ports: 
      - "8282:8080"
    depends_on:
      - postgres
    networks:
      mynet:
        ipv4_address: "172.28.1.2"
  view:
    image: view
    build: .
    env_file: 
      - .env
    volumes:
      - "./view/view:/view"
    command: ./view
    expose:
      - "8080"
    ports: 
      - "8383:8080"
    depends_on:
      - postgres
    networks:
      mynet:
        ipv4_address: "172.28.1.3"
  client:
    image: client
    build: .
    env_file: 
      - .env
    volumes:
      - "./client/client:/client"
    command: ./client
    networks:
      mynet:
        ipv4_address: "172.28.1.12"
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"
    ports: 
      - "15432:5432"
    networks:
      mynet:
        ipv4_address: "172.28.1.10"
    
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/16"